### ISSUE TITLE
Support multiple commands on the seq-cli docker image

### ISSUE THREAD

**Issue by bronumski** [datalust/seqcli#245]
I have a docker compose which sets up the seq web image and then sets up the api key but I can only run one command. I would also like to be able to setup some default signals. Currently I do this:

```
services:
  seq-cli:
    container_name: seq-cli
    image: datalust/seqcli:latest
    command: apikey create --title='default' --token='12345678901234567890' --server=http://seq-web
    depends_on:
      - seq-web
    restart: on-failure
    networks:
      - local-infrastructure

  seq-web:
    container_name: seq-web
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: 'Y'
    restart: unless-stopped
    networks:
      - local-infrastructure
    ports:
      - '5341:5341'
      - '5342:80'
```

Without duplicating a bunch of things I cannot run multiple commands. It would be nice to be able to do this:

```
  seq-cli:
    container_name: seq-cli
    image: datalust/seqcli:latest
    command:
      - apikey create --title='default' --token='12345678901234567890' --server=http://seq-web
      - signal create ...
```
