### ISSUE TITLE
Setting env var SEQCLI_CONNECTION_SERVERURL doesn't seem to work

### ISSUE THREAD

**Issue by richard-stafflink** [datalust/seqcli#365]
Documentation mentions being able to use env vars in the form `SEQCLI_<setting path>`, with the example: `SEQCLI_CONNECTION_SERVERURL`
But I wasn't able to get it working.

Steps to reproduce:

Create a docker compose file with the contents:
```yml
version: '3.7'

services:
  seq:
    container_name: local-seq
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - 81:80
      - 5341:5341
    environment:
      ACCEPT_EULA: 'Y'
    networks:
      - my_default

networks:
  my_default:
    name: my_default
```

Start the Seq container:
```bash
docker compose up -d --quiet-pull
```

Use the SeqCLI image to connect to it (using --server):
```bash
docker run --rm --network=my_default datalust/seqcli:latest feed list --server=http://local-seq
# nugetfeed-1 nuget.org
```

Use the SeqCLI image to connect to it (using env var `SEQCLI_CONNECTION_SERVERURL`):
```bash
docker run --rm --network=my_default -e SEQCLI_CONNECTION_SERVERURL=http://local-seq datalust/seqcli:latest feed list
# The command failed: Connection refused (localhost:5341) Connection refused
```

Confirm that env var `SEQCLI_CONNECTION_SERVERURL` gets passed to the container:
```bash
docker run --rm -it --entrypoint bash -e SEQCLI_CONNECTION_SERVERURL=http://local-seq --network=my_default datalust/seqcli:latest
# echo $SEQCLI_CONNECTION_SERVERURL
## http://local-seq
```
